{% set name = "types-scribe" %}
{% set version = "0.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-scribe-{{ version }}.tar.gz
  sha256: 4d72fa9ac0cbb3e5dc543979f1ddc54b04e593fdf4ee24b45f4c13ea6a812cb3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-fb303

test:
  commands:
    - test -f $SP_DIR/scribe-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for scribe
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
