{% set name = "types-scribe" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-scribe-{{ version }}.tar.gz
  sha256: 573ae400cfd46d9b4bf4574bf7035c7969cc25c396ed0789b42e0db6e1b92e66

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-fb303

test:
  commands:
    - test -f $SP_DIR/scribe-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for scribe
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
